### ISSUE TITLE
Username + email index is too long for production InnoDB implementation

### ISSUE THREAD

**Issue by iansltx** [joindin/joindin-api#663]
MariaDB tops out at 767 bytes for index keys. We have a username limit of 100 characters and an email limit of 200. Since we're using utf8mb4, that would require 1200 bytes for keys. This blocks conversion of the user table to InnoDB in production, from MyISAM, so #649 isn't quite complete.

The longest email address we have is 78 characters. The longest username we have is the full 100 characters, but the three accounts >= 72 characters all appear to be spam accounts anyway.

My suggestion here is to add a patch that bumps the username column down to 72 characters max, and email down to 100. If we want to notify the (suspected spam) accounts of their new usernames, easy enough to do so. In this patch we should rerun the InnoDB conversion for the user table so that when it's run in production we get rid of that last MyISAM table.

**Comment by heiglandreas** [comment]
When I see that right these are two indices. One for the username (100 characters * 4 = 400 byte so that shouldn't be an issue to convert) and one for the email-address (200 characters * 4 = 800 byte).

The index for the email-address therefore is 33bytes or 9 characters to long.

I'd therefore propose to reduce the email-address field to 190 characters.

**Comment by iansltx** [comment]
We have an index that includes a combination of username and email.

```
MariaDB [joindin]> show indexes from user\G
*************************** 1. row ***************************
        Table: user
   Non_unique: 0
     Key_name: PRIMARY
 Seq_in_index: 1
  Column_name: ID
    Collation: A
  Cardinality: 69859
     Sub_part: NULL
       Packed: NULL
         Null: 
   Index_type: BTREE
      Comment: 
Index_comment: 
*************************** 2. row ***************************
        Table: user
   Non_unique: 0
     Key_name: idx_username
 Seq_in_index: 1
  Column_name: username
    Collation: A
  Cardinality: NULL
     Sub_part: NULL
       Packed: NULL
         Null: YES
   Index_type: BTREE
      Comment: 
Index_comment: 
*************************** 3. row ***************************
        Table: user
   Non_unique: 0
     Key_name: idx_email_1
 Seq_in_index: 1
  Column_name: email
    Collation: A
  Cardinality: NULL
     Sub_part: NULL
       Packed: NULL
         Null: YES
   Index_type: BTREE
      Comment: 
Index_comment: 
*************************** 4. row ***************************
        Table: user
   Non_unique: 0
     Key_name: idx_email
 Seq_in_index: 1
  Column_name: email
    Collation: A
  Cardinality: NULL
     Sub_part: NULL
       Packed: NULL
         Null: YES
   Index_type: BTREE
      Comment: 
Index_comment: 
```
